package com.openlifting.domain.datasource

import com.openlifting.domain.model.EmgEvent
import com.openlifting.domain.model.SquatDepth
import com.openlifting.domain.model.SquatVariant
import kotlinx.coroutines.flow.Flow

/**
 * Source of EMG measurement events for a training set.
 *
 * Two implementations exist:
 *  - In-app simulator ([com.openlifting.data.simulator.Esp32Simulator]) for the offline
 *    demo and as fallback when the WebSocket source is unreachable.
 *  - WebSocket client (WebSocketEmgClient) that consumes the Python mock during
 *    development and an ESP32 broadcasting on Wi-Fi in production.
 *
 * Both implementations honour the wire protocol documented in
 * `docs/plan-realtime-measurement.md` §3 — they emit the same [EmgEvent] sequence so the
 * SessionViewModel state machine is source-agnostic.
 */
interface EmgDataSource {

    /**
     * Starts a set with the given parameters and returns a cold flow of measurement
     * events. The flow closes after [EmgEvent.SetComplete] or [EmgEvent.Error]. Cancelling
     * the flow before completion should be honoured by the implementation (e.g. close the
     * WebSocket, stop the simulator coroutine).
     *
     * @param request stable parameters for the set; [StartSetRequest.setRequestId] is
     *                generated by the caller to correlate request and stream.
     */
    fun streamSet(request: StartSetRequest): Flow<EmgEvent>
}

/**
 * Request sent to start a new set. Mirrors the JSON payload the Android client sends to
 * the WebSocket server (§3.2 of the realtime-measurement plan).
 *
 * [rpe] is the athlete's Rate of Perceived Exertion (1-10). It is used by the simulator
 * to scale rep velocity: higher RPE → slower reps (closer to 1RM). The Python mock or
 * real ESP32 may ignore it and use fixed timings — the field is optional.
 */
data class StartSetRequest(
    val setRequestId: String,
    val loadKg: Float,
    val targetReps: Int,
    val variant: SquatVariant,
    val depth: SquatDepth,
    val rpe: Float? = null,
    val athleteId: String? = null
)
